
name: my-GH-Act


on: 
  push:
    branches: [ master ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: check that everything is installed
        run: ls -la
        
 
      ######################################################

      - name: Install Apache
        run: |
          pwd
          sudo apt update
          sudo apt install apache2
          echo "GETTING ADMIN PERMS SETUP"


          sudo adduser $(whoami) www-data
          sudo adduser $(whoami) root
          sudo adduser root www-data

          sudo chown -R www-data:www-data /etc/apache2/sites-available/
          sudo chmod -R 777 /etc/apache2/sites-available/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 777 /var/www/html/
          
          


        





